apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: ghost-hourly
  namespace: ghost
spec:
  appVaultRef: argocdtest
  applicationRef: ghost
  backupRetention: "1"
  dayOfMonth: ""
  dayOfWeek: ""
  granularity: Hourly
  hour: ""
  minute: "50"
  snapshotRetention: "1"
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: ghost-daily
  namespace: ghost
spec:
  appVaultRef: argocdtest
  applicationRef: ghost
  backupRetention: "1"
  dayOfMonth: ""
  dayOfWeek: ""
  granularity: Daily
  hour: "1"
  minute: "0"
  snapshotRetention: "1"
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: ghost-weekly
  namespace: ghost
spec:
  appVaultRef: argocdtest
  applicationRef: ghost
  backupRetention: "1"
  dayOfMonth: ""
  dayOfWeek: "7"
  granularity: Weekly
  hour: "2"
  minute: "0"
  snapshotRetention: "1"
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: ghost-monthly
  namespace: ghost
spec:
  appVaultRef: argocdtest
  applicationRef: ghost
  backupRetention: "1"
  dayOfMonth: "1"
  dayOfWeek: ""
  granularity: Monthly
  hour: "2"
  minute: "20"
  snapshotRetention: "1"